### ISSUE TITLE
User Story 1 Donorpage

### ISSUE THREAD

**Issue by minatimar** [minatimar/capstone-project#1]
## Value Proposition

**As a** User
**I want to** have an overview of the donations 
**so that**  I can choose what I like to save 

## Description

![Untitled-2023-01-18-1137](https://user-images.githubusercontent.com/118187861/213715261-21a6e3c6-4392-4b64-aef7-1b9c270b9891.png)

## Acceptance Criteria

- [ ] The app title/header is displayed on the top and always visible
- [ ] each donation card displays an image of the donation
- [ ] each donation card displays a description
- [ ] each donation card displays a distance to the donor

## Tasks

- [ ] create a Header that is fixed in the top position
- [ ] create db.json for dummy data for the Cards 
- [ ] create a card component to render each donation object
- [ ] add remotePatterns for next/image

## Complexity

- M

**Comment by mbosselmann** [comment]
Hi Mina,
well defined and small user story, but we have some remarks for you:

**Value proposition**
- your value proposition is very good, but you should format the value proposition correctly:

**As a** User
**I want to** have an overview of the donations
**so that** I can choose what I like to save

**Description**
- "Kontaktieren" and "Kontaktdaten" are inconsistent

**Acceptance criteria**
- you should describe in more details what the acceptance criteria are
- instead of writing "Logo/Header" for example " The app title is displayed on the top and always visible"
- "each donation card displays an image of the donation"
- "each donation card displays a category"
- "each donation card displays a description"
- etc.
- your list is also not formatted correctly: when you write "- [ ]" the checkmarks should be displayed

**Tasks**
- also your tasks should be listed with checkmarks
- two more tasks that you could add: 
- "create a card component to render each donation object"
- "add remotePatterns for next/image"
- you could add an example for your data structure if you already thought about it

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by F-Kirchhoff** [comment]
Hey Mina,
very nice job 👍 . You need to add only one acceptance criteria, but that is a very minor point:
- every item of the db is displayed as a card

I will approve your user story anyways, because I believe in you that you can add this point :D. I have a little suggestion for you besides the user story:
- your wireframe looks a bit as if there won't be enough space for all the text in your card or that the formatting might look quite bloated on a small screen. Try to find the most important informations and focus on them. A good UI guides the user visually to the important stuff and hides the minor points and doesn't overwhelm the user. Try to think about this when you implement the user story :)

**Comment by F-Kirchhoff** [comment]
Hey Mina, I really love the idea of the more infos button! Does the button have a functionality? Because if I can click on the button but it doesn't do anything you need to put it in the next user story, no loose strings in your app design 🙈

**Comment by F-Kirchhoff** [comment]
Amazing, great work. LGTM 🦊

**Comment by mbosselmann** [comment]
Happy hacking, Mina! 🚀 You rock! 🪨
