### ISSUE TITLE
User Story 5 Navigation Bar

### ISSUE THREAD

**Issue by minatimar** [minatimar/capstone-project#10]
## Value Proposition

**As a** User
**I want to** have a navigation bar  
**so that** I can quickly switch between pages

## Description

![UserStory5](https://user-images.githubusercontent.com/118187861/217228867-070ab4a5-3bd1-43b8-b620-192e26dae0df.png)

## Acceptance Criteria

- [ ] the navigation bar should be displayed fixed at the bottom of both pages
- [ ] the navigation bar should take me to the other page, either the donation page or to the rescue page
- [ ] the navigation bar should have another text/link depending on which page I am

## Tasks

- [ ] create a fixed navigation bar at the bottom of each page
- [ ] the navigation bar should be clickable and send you to the respective page 

## Complexity

S

**Comment by niklasrammelkamp** [comment]
nice one
