### ISSUE TITLE
User Story 6 Homepage

### ISSUE THREAD

**Issue by minatimar** [minatimar/capstone-project#12]
## Value Proposition

**As a** User
**I want to** be welcomed on a homepage    
**so that** I can choose wether to donate or save some food
 
## Description
![UserStory 6 Homepage](https://user-images.githubusercontent.com/118187861/217829876-43d0892c-96ef-46c6-8edf-fd7a90d2a16c.png)

## Acceptance Criteria

- [ ] i want to have home page with a nice logo
- [ ] two buttons, one for saving and one for donating
- [ ] one button sends me to the donation page
- [ ] the other button sends me to the saving page

## Tasks

- [ ] create a homepage
- [ ] put an h1 and a logo on the side
- [ ] two links styled as a button
- [ ] one link to the donor page and one to the saving page 

## Complexity

S

**Comment by anotherMichaelMaier** [comment]
Looks like a good and compact US to me.
