### ISSUE TITLE
User Story 8 Styling

### ISSUE THREAD

**Issue by minatimar** [minatimar/capstone-project#15]
## Value Proposition

**As a** User
**I want to** visit a visually appealing app  
**so that** I enjoy spending time on it

## Description

![userstory7styling](https://user-images.githubusercontent.com/118187861/218059525-a3ad4982-cc61-4813-b45f-0372fbffb032.png)

## Acceptance Criteria

- [ ] add a color scheme with color green, orange, magenta and creme 
- [ ] see a dummy picture of the donation

## Tasks

- [ ]  add different colors to the header, buttons and navbar 
- [ ] the checkboxes should be displayed next to each other not below each other
- [ ] add a dummy picture to the dummy donations 

## Complexity

M
