### ISSUE TITLE
User Story 7 Filter

### ISSUE THREAD

**Issue by minatimar** [minatimar/capstone-project#16]
## Value Proposition

**As a** User
**I want to** I want to be able to filter all donations by zipcode
**so that** I know what is close to me

## Description

![UserStory8](https://user-images.githubusercontent.com/118187861/218068921-1154744f-18ee-4b6d-872b-3bacd0b333de.png)

## Acceptance Criteria

- [ ] add an input field for the zipcode
- [ ] the filter should filter the donations to the searched zipcode

## Tasks

- [ ] add an input field 
- [ ] the input field should have an onchange function 
- [ ] the filter function should filter all donations and only show donations in my chooses zipcode

## Complexity

M
