### ISSUE TITLE
User Story 2 Detailpage Donations

### ISSUE THREAD

**Issue by minatimar** [minatimar/capstone-project#2]
## Value Proposition

**As a** Foodsaver
**I want to** be able to see all the Details of the Donation, via "more Info" Button"  
**so that** I can choose if I like it 

## Description

![Image](https://user-images.githubusercontent.com/118187861/214036978-4e087dd6-283c-4731-a88b-8bda79b28f30.png)

## Acceptance Criteria

- [ ] Add two Buttons "more Info" and "back" with a toggle function
- [ ]  "more Info" Button has to render Card with details
- [ ] "back" Button has to render Card with fewer details

## Tasks

- [ ] create "more Info"- Button that when clicked renders all the details
- [ ] create "back"- Button on the card with all the details, that when clicked hides all details but two. 

## Complexity

M

**Comment by anotherMichaelMaier** [comment]
Hey Mina, you could write down what details you mean.
But it doesn't bother me to much.
So lgtm. :)
