### ISSUE TITLE
User Story 3 My Donations

### ISSUE THREAD

**Issue by minatimar** [minatimar/capstone-project#6]
## Value Proposition

**As a** Donor
**I want to** have an overview of my donations  
**so that** I can add or delete some donations

## Description
![UserStory3](https://user-images.githubusercontent.com/118187861/214599551-d521a24c-8b27-410a-9c4f-f3528bb80706.png)

## Acceptance Criteria

- [x] the cards with my already made donations should be shown 
- [x] a delete button should be on the donation card
- [x] the delete button deletes the card if you click on it
- [x]  an add-button is displayed on top of the page
- [x] if you click on the add-button it opens input fields, checkboxes and dropdown field
- [x] the new donations also has two buttons back and submit
- [x] the back buttons deletes everything and brings you back to the site my donations
- [x] the submit button submits your donation

## Tasks

- [x] add an clickable add button on each donation card
- [x] add a clickable delete button o each donation card
- [x] add the donation page with input fields, dropdown and checkboxes

## Complexity

L

**Comment by marcterre** [comment]
Hey Mina, in your Acceptance Criteria you mentioned a few buttons, what happens if i click on them? If the buttons cant do anything you shouldnt mention them. Else you can write it like that: 
- [ ] an add-button is displayed on top of the page
- [ ] if you click the add-button... (whatever it does)
Same for the delete button.
In relation to above i would split ur user story. In this user story you can add the "add-button" and the "delete-button" (with functionality) and in the next user story you can add the navigation or the other way however you like it.
In your acceptance criteria you should mention what your navigation does, for example:
- [ ] in the navigation there a three Links displayed with icons
- [ ] the "home"-icon leads to the landingpage
Also important that you describe where your link leads. Dont forget to update your wireframe. You can use arrows to point to other pages.

**Comment by minatimar** [comment]
Hi Marc, thank you for your remarks, i changed my user story and added more details and changed the complexity to L.

**Comment by anotherMichaelMaier** [comment]
Looks good to me, I told you about the points I would improve and as I can see you reworked your US already after Marcs comment.
