### ISSUE TITLE
User Story 4 - Edit-Button

### ISSUE THREAD

**Issue by minatimar** [minatimar/capstone-project#8]
## Value Proposition

**As a** User 
**I want to** to edit my Donation 
**so that** I can adjust my Donation 

## Description

![US4](https://user-images.githubusercontent.com/118187861/216057046-9b2cbcf9-9d2a-4908-9f72-33ecc6defd05.png)

## Acceptance Criteria

- [ ] the edit- button should be displayed on my donation card, for further changes
- [ ] the edit-button should open the donation-card so you can edit the donation and save it or go back to the donation page

## Tasks

- [ ] create an Edit-Button 
- [ ] create an edit page where your old values are displayed
- [ ] create a save button on the edit page to save changes and go back to the donation page
- [ ] create an cancel button to go back to the donation page without changing anything

## Complexity

S

**Comment by niklasrammelkamp** [comment]
hey mina, nice but looks like two user stories to me. 
Do you want to implement edit functionality to the edit button? 
'Cause if not you have a button that does nothing and that's not good otherwise if you want to add the functionality I would put that in an extra user story and describe the tasks in more detail.
Because these two things are not dependent on each other. So you can make a small userstory for navigation and one for the edit functionality. Then you have two small user stories you can easily work with.
That's my suggestion.

**Comment by minatimar** [comment]
thank you - i changed it into two user stories now
